[2020-04-26 18:54:28,934] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:42:44.363392+00:00 [queued]>
[2020-04-26 18:54:28,964] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:42:44.363392+00:00 [queued]>
[2020-04-26 18:54:28,964] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 18:54:28,965] {{taskinstance.py:867}} INFO - Starting attempt 2 of 2
[2020-04-26 18:54:28,965] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 18:54:28,991] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): persiste_dados_mongodb> on 2020-04-26T17:42:44.363392+00:00
[2020-04-26 18:54:28,998] {{standard_task_runner.py:53}} INFO - Started process 15235 to run task
[2020-04-26 18:54:29,078] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:42:44.363392+00:00 [running]> 030a07de9129.semantix
[2020-04-26 18:54:29,107] {{taskinstance.py:1128}} ERROR - crud_main() missing 5 required positional arguments: 'metod', 'company', 'collection', 'date', and 'jsondata'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: crud_main() missing 5 required positional arguments: 'metod', 'company', 'collection', 'date', and 'jsondata'
[2020-04-26 18:54:29,110] {{taskinstance.py:1170}} INFO - All retries failed; marking task as FAILED.dag_id=ReclameAqui, task_id=persiste_dados_mongodb, execution_date=20200426T174244, start_date=20200426T185428, end_date=20200426T185429
[2020-04-26 18:54:38,905] {{logging_mixin.py:112}} INFO - [2020-04-26 18:54:38,905] {{local_task_job.py:103}} INFO - Task exited with return code 1
