[2020-04-26 19:38:41,727] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.consulta_dados_company 2020-04-26T19:38:35.861836+00:00 [queued]>
[2020-04-26 19:38:41,788] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.consulta_dados_company 2020-04-26T19:38:35.861836+00:00 [queued]>
[2020-04-26 19:38:41,789] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 19:38:41,791] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 19:38:41,792] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 19:38:41,843] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): consulta_dados_company> on 2020-04-26T19:38:35.861836+00:00
[2020-04-26 19:38:41,857] {{standard_task_runner.py:53}} INFO - Started process 10298 to run task
[2020-04-26 19:38:42,112] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.consulta_dados_company 2020-04-26T19:38:35.861836+00:00 [running]> 030a07de9129.semantix
[2020-04-26 19:38:42,258] {{logging_mixin.py:112}} INFO - 200
[2020-04-26 19:38:42,259] {{logging_mixin.py:112}} INFO - {"20200426CIELO": {"company": "Cielo", "date": "20200426", "answered": "6666", "reclamations": "6151", "response_time": "15 dias e 21 horas ", "unanswered": "113"}}
[2020-04-26 19:38:42,260] {{python_operator.py:114}} INFO - Done. Returned value was: None
[2020-04-26 19:38:42,298] {{taskinstance.py:1048}} INFO - Marking task as SUCCESS.dag_id=ReclameAqui, task_id=consulta_dados_company, execution_date=20200426T193835, start_date=20200426T193841, end_date=20200426T193842
[2020-04-26 19:38:51,633] {{logging_mixin.py:112}} INFO - [2020-04-26 19:38:51,633] {{local_task_job.py:103}} INFO - Task exited with return code 0
