[2020-04-26 20:24:59,481] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.consulta_dados_company2 2020-04-26T20:24:42.230047+00:00 [queued]>
[2020-04-26 20:24:59,547] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.consulta_dados_company2 2020-04-26T20:24:42.230047+00:00 [queued]>
[2020-04-26 20:24:59,548] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:24:59,549] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 20:24:59,550] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:24:59,579] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): consulta_dados_company2> on 2020-04-26T20:24:42.230047+00:00
[2020-04-26 20:24:59,586] {{standard_task_runner.py:53}} INFO - Started process 7118 to run task
[2020-04-26 20:24:59,716] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.consulta_dados_company2 2020-04-26T20:24:42.230047+00:00 [running]> 030a07de9129.semantix
[2020-04-26 20:24:59,770] {{logging_mixin.py:112}} INFO - DEBUG GET: {'company': 'Cielo'}
[2020-04-26 20:24:59,786] {{logging_mixin.py:112}} INFO - 200
[2020-04-26 20:24:59,787] {{logging_mixin.py:112}} INFO - {}
[2020-04-26 20:24:59,788] {{python_operator.py:114}} INFO - Done. Returned value was: None
[2020-04-26 20:24:59,808] {{taskinstance.py:1048}} INFO - Marking task as SUCCESS.dag_id=ReclameAqui, task_id=consulta_dados_company2, execution_date=20200426T202442, start_date=20200426T202459, end_date=20200426T202459
[2020-04-26 20:25:09,409] {{logging_mixin.py:112}} INFO - [2020-04-26 20:25:09,408] {{local_task_job.py:103}} INFO - Task exited with return code 0
