[2020-04-26 17:17:45,509] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:17:40.083377+00:00 [queued]>
[2020-04-26 17:17:45,532] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:17:40.083377+00:00 [queued]>
[2020-04-26 17:17:45,532] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:17:45,532] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 17:17:45,532] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:17:45,549] {{taskinstance.py:887}} INFO - Executing <Task(BashOperator): persiste_dados_mongodb> on 2020-04-26T17:17:40.083377+00:00
[2020-04-26 17:17:45,553] {{standard_task_runner.py:53}} INFO - Started process 23149 to run task
[2020-04-26 17:17:45,622] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:17:40.083377+00:00 [running]> 61b2702b37e2.semantix
[2020-04-26 17:17:45,647] {{bash_operator.py:82}} INFO - Tmp dir root location: 
 /tmp
[2020-04-26 17:17:45,648] {{bash_operator.py:105}} INFO - Temporary script location: /tmp/airflowtmptqsjsf6r/persiste_dados_mongodbjfi6r4yj
[2020-04-26 17:17:45,648] {{bash_operator.py:115}} INFO - Running command: /usr/local/airflow/dags/scripts/requests_database.py --metod POST --company Cielo --collection scores --jsondata {'answered': '6666', 'reclamations': '6151', 'response_time': '15 dias e 21 horas ', 'unanswered': '113'}
[2020-04-26 17:17:45,655] {{bash_operator.py:122}} INFO - Output:
[2020-04-26 17:17:45,658] {{bash_operator.py:126}} INFO - /usr/local/airflow/dags/scripts/requests_database.py: line 5: $'\nDate: 20190506\nUser: Alan Viegas\nProject: WebScrap ReclameAqui\n': command not found
[2020-04-26 17:17:45,659] {{bash_operator.py:126}} INFO - /usr/local/airflow/dags/scripts/requests_database.py: line 7: import: command not found
[2020-04-26 17:17:45,659] {{bash_operator.py:126}} INFO - /usr/local/airflow/dags/scripts/requests_database.py: line 8: import: command not found
[2020-04-26 17:17:45,660] {{bash_operator.py:126}} INFO - /usr/local/airflow/dags/scripts/requests_database.py: line 9: import: command not found
[2020-04-26 17:17:45,661] {{bash_operator.py:126}} INFO - /usr/local/airflow/dags/scripts/requests_database.py: line 10: import: command not found
[2020-04-26 17:17:45,661] {{bash_operator.py:126}} INFO - /usr/local/airflow/dags/scripts/requests_database.py: line 12: syntax error near unexpected token `('
[2020-04-26 17:17:45,661] {{bash_operator.py:126}} INFO - /usr/local/airflow/dags/scripts/requests_database.py: line 12: `def post_database(collection, params, jsondata):'
[2020-04-26 17:17:45,661] {{bash_operator.py:130}} INFO - Command exited with return code 2
[2020-04-26 17:17:45,674] {{taskinstance.py:1128}} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-04-26 17:17:45,676] {{taskinstance.py:1151}} INFO - Marking task as UP_FOR_RETRY
[2020-04-26 17:17:55,505] {{logging_mixin.py:112}} INFO - [2020-04-26 17:17:55,504] {{local_task_job.py:103}} INFO - Task exited with return code 1
