[2020-04-26 20:06:31,895] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.consulta_dados_company_date 2020-04-26T20:06:24.095188+00:00 [queued]>
[2020-04-26 20:06:31,936] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.consulta_dados_company_date 2020-04-26T20:06:24.095188+00:00 [queued]>
[2020-04-26 20:06:31,937] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:06:31,937] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 20:06:31,939] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:06:31,979] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): consulta_dados_company_date> on 2020-04-26T20:06:24.095188+00:00
[2020-04-26 20:06:31,984] {{standard_task_runner.py:53}} INFO - Started process 27829 to run task
[2020-04-26 20:06:32,084] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.consulta_dados_company_date 2020-04-26T20:06:24.095188+00:00 [running]> 030a07de9129.semantix
[2020-04-26 20:06:32,118] {{logging_mixin.py:112}} INFO - DEBUG GET: {'company': 'Cielo', 'date': '20190101'}
[2020-04-26 20:06:32,119] {{logging_mixin.py:112}} INFO - DEBUG GET 1: http://api_persistenciadados:5005/scores/
[2020-04-26 20:06:32,119] {{logging_mixin.py:112}} INFO - DEBUG GET 2: {'company': 'Cielo', 'date': '20190101'}
[2020-04-26 20:06:32,127] {{logging_mixin.py:112}} INFO - DEBUG GET 3: {"20200426CIELO": {"company": "Cielo", "date": "20200426", "answered": "6666", "reclamations": "6151", "response_time": "15 dias e 21 horas ", "unanswered": "113"}, "20190101CIELO": {"company": "Cielo", "date": "20190101", "answered": "6666", "reclamations": "6151", "response_time": "15 dias e 21 horas ", "unanswered": "113"}}
[2020-04-26 20:06:32,127] {{logging_mixin.py:112}} INFO - 200
[2020-04-26 20:06:32,127] {{logging_mixin.py:112}} INFO - {"20200426CIELO": {"company": "Cielo", "date": "20200426", "answered": "6666", "reclamations": "6151", "response_time": "15 dias e 21 horas ", "unanswered": "113"}, "20190101CIELO": {"company": "Cielo", "date": "20190101", "answered": "6666", "reclamations": "6151", "response_time": "15 dias e 21 horas ", "unanswered": "113"}}
[2020-04-26 20:06:32,127] {{python_operator.py:114}} INFO - Done. Returned value was: None
[2020-04-26 20:06:32,153] {{taskinstance.py:1048}} INFO - Marking task as SUCCESS.dag_id=ReclameAqui, task_id=consulta_dados_company_date, execution_date=20200426T200624, start_date=20200426T200631, end_date=20200426T200632
[2020-04-26 20:06:41,817] {{logging_mixin.py:112}} INFO - [2020-04-26 20:06:41,816] {{local_task_job.py:103}} INFO - Task exited with return code 0
