[2020-04-26 20:16:28,883] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.consulta_dados_company_2 2020-04-26T20:16:22.049547+00:00 [queued]>
[2020-04-26 20:16:28,914] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.consulta_dados_company_2 2020-04-26T20:16:22.049547+00:00 [queued]>
[2020-04-26 20:16:28,915] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:16:28,915] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 20:16:28,915] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:16:28,962] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): consulta_dados_company_2> on 2020-04-26T20:16:22.049547+00:00
[2020-04-26 20:16:28,967] {{standard_task_runner.py:53}} INFO - Started process 1677 to run task
[2020-04-26 20:16:29,075] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.consulta_dados_company_2 2020-04-26T20:16:22.049547+00:00 [running]> 030a07de9129.semantix
[2020-04-26 20:16:29,111] {{logging_mixin.py:112}} INFO - DEBUG GET: {'company': 'Cielo'}
[2020-04-26 20:16:29,134] {{logging_mixin.py:112}} INFO - 200
[2020-04-26 20:16:29,134] {{logging_mixin.py:112}} INFO - {"20190101CIELO": {"company": "Cielo", "date": "20190101", "answered": "6666", "reclamations": "6151", "response_time": "15 dias e 21 horas ", "unanswered": "113"}}
[2020-04-26 20:16:29,135] {{python_operator.py:114}} INFO - Done. Returned value was: None
[2020-04-26 20:16:29,156] {{taskinstance.py:1048}} INFO - Marking task as SUCCESS.dag_id=ReclameAqui, task_id=consulta_dados_company_2, execution_date=20200426T201622, start_date=20200426T201628, end_date=20200426T201629
[2020-04-26 20:16:38,721] {{logging_mixin.py:112}} INFO - [2020-04-26 20:16:38,720] {{local_task_job.py:103}} INFO - Task exited with return code 0
