[2020-04-26 20:56:49,737] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui-scraping_scores.scores_reclameaqui 2020-04-25T00:00:00+00:00 [queued]>
[2020-04-26 20:56:49,791] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui-scraping_scores.scores_reclameaqui 2020-04-25T00:00:00+00:00 [queued]>
[2020-04-26 20:56:49,793] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:56:49,808] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 20:56:49,809] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:56:49,861] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): scores_reclameaqui> on 2020-04-25T00:00:00+00:00
[2020-04-26 20:56:49,871] {{standard_task_runner.py:53}} INFO - Started process 26722 to run task
[2020-04-26 20:56:49,974] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui-scraping_scores.scores_reclameaqui 2020-04-25T00:00:00+00:00 [running]> 030a07de9129.semantix
[2020-04-26 20:56:50,662] {{logging_mixin.py:112}} INFO - 404
[2020-04-26 20:56:50,662] {{logging_mixin.py:112}} INFO - <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
[2020-04-26 20:56:50,663] {{logging_mixin.py:112}} INFO - 
[2020-04-26 20:56:50,664] {{python_operator.py:114}} INFO - Done. Returned value was: None
[2020-04-26 20:56:50,706] {{taskinstance.py:1048}} INFO - Marking task as SUCCESS.dag_id=ReclameAqui-scraping_scores, task_id=scores_reclameaqui, execution_date=20200425T000000, start_date=20200426T205649, end_date=20200426T205650
[2020-04-26 20:56:59,648] {{logging_mixin.py:112}} INFO - [2020-04-26 20:56:59,647] {{local_task_job.py:103}} INFO - Task exited with return code 0
[2020-04-26 22:49:46,327] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui-scraping_scores.scores_reclameaqui 2020-04-25T00:00:00+00:00 [queued]>
[2020-04-26 22:49:46,369] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui-scraping_scores.scores_reclameaqui 2020-04-25T00:00:00+00:00 [queued]>
[2020-04-26 22:49:46,369] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 22:49:46,369] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 22:49:46,369] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 22:49:46,386] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): scores_reclameaqui> on 2020-04-25T00:00:00+00:00
[2020-04-26 22:49:46,390] {{standard_task_runner.py:53}} INFO - Started process 31366 to run task
[2020-04-26 22:49:46,458] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui-scraping_scores.scores_reclameaqui 2020-04-25T00:00:00+00:00 [running]> 030a07de9129.semantix
[2020-04-26 22:49:46,483] {{taskinstance.py:1128}} ERROR - get_reclameaqui() got an unexpected keyword argument 'conf'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: get_reclameaqui() got an unexpected keyword argument 'conf'
[2020-04-26 22:49:46,484] {{taskinstance.py:1151}} INFO - Marking task as UP_FOR_RETRY
[2020-04-26 22:49:56,318] {{logging_mixin.py:112}} INFO - [2020-04-26 22:49:56,317] {{local_task_job.py:103}} INFO - Task exited with return code 1
