[2020-04-26 20:24:10,040] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.consulta_dados_company 2020-04-26T20:23:55.239072+00:00 [queued]>
[2020-04-26 20:24:10,097] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.consulta_dados_company 2020-04-26T20:23:55.239072+00:00 [queued]>
[2020-04-26 20:24:10,098] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:24:10,098] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 20:24:10,098] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:24:10,116] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): consulta_dados_company> on 2020-04-26T20:23:55.239072+00:00
[2020-04-26 20:24:10,121] {{standard_task_runner.py:53}} INFO - Started process 6555 to run task
[2020-04-26 20:24:10,234] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.consulta_dados_company 2020-04-26T20:23:55.239072+00:00 [running]> 030a07de9129.semantix
[2020-04-26 20:24:10,286] {{logging_mixin.py:112}} INFO - DEBUG GET: {'company': 'Cielo'}
[2020-04-26 20:24:10,313] {{logging_mixin.py:112}} INFO - 200
[2020-04-26 20:24:10,314] {{logging_mixin.py:112}} INFO - {}
[2020-04-26 20:24:10,315] {{python_operator.py:114}} INFO - Done. Returned value was: None
[2020-04-26 20:24:10,336] {{taskinstance.py:1048}} INFO - Marking task as SUCCESS.dag_id=ReclameAqui, task_id=consulta_dados_company, execution_date=20200426T202355, start_date=20200426T202410, end_date=20200426T202410
[2020-04-26 20:24:19,982] {{logging_mixin.py:112}} INFO - [2020-04-26 20:24:19,981] {{local_task_job.py:103}} INFO - Task exited with return code 0
