[2020-04-26 20:24:50,975] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.consulta_dados_company 2020-04-26T20:24:42.230047+00:00 [queued]>
[2020-04-26 20:24:51,001] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.consulta_dados_company 2020-04-26T20:24:42.230047+00:00 [queued]>
[2020-04-26 20:24:51,002] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:24:51,002] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 20:24:51,002] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:24:51,022] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): consulta_dados_company> on 2020-04-26T20:24:42.230047+00:00
[2020-04-26 20:24:51,026] {{standard_task_runner.py:53}} INFO - Started process 7011 to run task
[2020-04-26 20:24:51,088] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.consulta_dados_company 2020-04-26T20:24:42.230047+00:00 [running]> 030a07de9129.semantix
[2020-04-26 20:24:51,109] {{logging_mixin.py:112}} INFO - DEBUG GET: {'company': 'Cielo'}
[2020-04-26 20:24:51,117] {{logging_mixin.py:112}} INFO - 200
[2020-04-26 20:24:51,118] {{logging_mixin.py:112}} INFO - {"20190101CIELO": {"company": "Cielo", "date": "20190101", "answered": "6666", "reclamations": "6151", "response_time": "15 dias e 21 horas ", "unanswered": "113"}}
[2020-04-26 20:24:51,118] {{python_operator.py:114}} INFO - Done. Returned value was: None
[2020-04-26 20:24:51,129] {{taskinstance.py:1048}} INFO - Marking task as SUCCESS.dag_id=ReclameAqui, task_id=consulta_dados_company, execution_date=20200426T202442, start_date=20200426T202450, end_date=20200426T202451
[2020-04-26 20:25:00,953] {{logging_mixin.py:112}} INFO - [2020-04-26 20:25:00,953] {{local_task_job.py:103}} INFO - Task exited with return code 0
