[2020-04-26 17:23:43,312] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:23:36.784875+00:00 [queued]>
[2020-04-26 17:23:43,382] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:23:36.784875+00:00 [queued]>
[2020-04-26 17:23:43,384] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:23:43,384] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 17:23:43,385] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:23:43,468] {{taskinstance.py:887}} INFO - Executing <Task(BashOperator): persiste_dados_mongodb> on 2020-04-26T17:23:36.784875+00:00
[2020-04-26 17:23:43,484] {{standard_task_runner.py:53}} INFO - Started process 26946 to run task
[2020-04-26 17:23:43,767] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:23:36.784875+00:00 [running]> 61b2702b37e2.semantix
[2020-04-26 17:23:43,869] {{bash_operator.py:82}} INFO - Tmp dir root location: 
 /tmp
[2020-04-26 17:23:43,875] {{bash_operator.py:105}} INFO - Temporary script location: /tmp/airflowtmpyav3twjg/persiste_dados_mongodbm1suieex
[2020-04-26 17:23:43,876] {{bash_operator.py:115}} INFO - Running command: /usr/local/airflow/dags/scripts/requests_database.py --metod POST --company Cielo --collection scores --jsondata {'answered': '6666', 'reclamations': '6151', 'response_time': '15 dias e 21 horas ', 'unanswered': '113'}
[2020-04-26 17:23:43,895] {{bash_operator.py:122}} INFO - Output:
[2020-04-26 17:23:43,966] {{bash_operator.py:126}} INFO -   File "/usr/local/airflow/dags/scripts/requests_database.py", line 52
[2020-04-26 17:23:43,967] {{bash_operator.py:126}} INFO -     main_response = get_database(collection, params):
[2020-04-26 17:23:43,967] {{bash_operator.py:126}} INFO -                                                     ^
[2020-04-26 17:23:43,968] {{bash_operator.py:126}} INFO - SyntaxError: invalid syntax
[2020-04-26 17:23:43,981] {{bash_operator.py:130}} INFO - Command exited with return code 1
[2020-04-26 17:23:44,011] {{taskinstance.py:1128}} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-04-26 17:23:44,016] {{taskinstance.py:1151}} INFO - Marking task as UP_FOR_RETRY
[2020-04-26 17:23:53,261] {{logging_mixin.py:112}} INFO - [2020-04-26 17:23:53,261] {{local_task_job.py:103}} INFO - Task exited with return code 1
