[2020-04-26 17:28:47,067] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:23:36.784875+00:00 [queued]>
[2020-04-26 17:28:47,089] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:23:36.784875+00:00 [queued]>
[2020-04-26 17:28:47,090] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:28:47,090] {{taskinstance.py:867}} INFO - Starting attempt 2 of 2
[2020-04-26 17:28:47,090] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 17:28:47,106] {{taskinstance.py:887}} INFO - Executing <Task(BashOperator): persiste_dados_mongodb> on 2020-04-26T17:23:36.784875+00:00
[2020-04-26 17:28:47,112] {{standard_task_runner.py:53}} INFO - Started process 30180 to run task
[2020-04-26 17:28:47,188] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T17:23:36.784875+00:00 [running]> 61b2702b37e2.semantix
[2020-04-26 17:28:47,209] {{bash_operator.py:82}} INFO - Tmp dir root location: 
 /tmp
[2020-04-26 17:28:47,211] {{bash_operator.py:105}} INFO - Temporary script location: /tmp/airflowtmpi31f4grt/persiste_dados_mongodbmkqv68ci
[2020-04-26 17:28:47,211] {{bash_operator.py:115}} INFO - Running command: /usr/local/airflow/dags/scripts/requests_database.py --metod 'POST' --company 'Cielo' --collection 'scores' --jsondata '{'answered': '6666', 'reclamations': '6151', 'response_time': '15 dias e 21 horas ', 'unanswered': '113'}'
[2020-04-26 17:28:47,218] {{bash_operator.py:122}} INFO - Output:
[2020-04-26 17:28:47,416] {{bash_operator.py:126}} INFO - usage: requests_database.py [-h] --metod METOD --company COMPANY --collection
[2020-04-26 17:28:47,416] {{bash_operator.py:126}} INFO -                             COLLECTION [--date DATE] [--jsondata JSONDATA]
[2020-04-26 17:28:47,417] {{bash_operator.py:126}} INFO - requests_database.py: error: unrecognized arguments: dias e 21 horas , unanswered: 113}
[2020-04-26 17:28:47,417] {{bash_operator.py:126}} INFO - Inicio processo
[2020-04-26 17:28:47,433] {{bash_operator.py:130}} INFO - Command exited with return code 2
[2020-04-26 17:28:47,442] {{taskinstance.py:1128}} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-04-26 17:28:47,443] {{taskinstance.py:1170}} INFO - All retries failed; marking task as FAILED.dag_id=ReclameAqui, task_id=persiste_dados_mongodb, execution_date=20200426T172336, start_date=20200426T172847, end_date=20200426T172847
[2020-04-26 17:28:57,070] {{logging_mixin.py:112}} INFO - [2020-04-26 17:28:57,069] {{local_task_job.py:103}} INFO - Task exited with return code 1
